class_name PossessionNode
extends RefCounted


enum Value {
	DEAD_BALL,
	INBOUND,
	ADVANCE,
	TRANSITION_DECISION,
	HALF_COURT_ENTRY,
	ACTION_SELECTION,
	ACTION_EXECUTION,
	ADVANTAGE_STATE,
	SHOT_SETUP,
	SHOT_RESOLUTION,
	FOUL_RESOLUTION,
	REBOUND_RESOLUTION,
	PUTBACK_DECISION,
	POSSESSION_END,
}
